dist: bionic

jobs:
  include:
  - name: Kong CE 2.4.x
    env: KONG_VERSION=2.4.x
  - name: Kong CE Master
    env: KONG_VERSION=nightly
  - name: Kong EE 2.4.1.x
    env: KONG_VERSION=2.4.1.x
  - name: Kong Enterprise nightly
    env: KONG_VERSION=nightly-ee

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: jeyfYnQslOOjT+kVHSNWeKPKEjDxwYDpygd3SuAbnchmlrog90wgBcjmPxIRTP0R5cEXDmIw45LjFM4srdZT4vf5Whykznz6IkQ7NeHs5cpk8aDK9Ya3dv+NNbbq3TPyKa6G7B/DnVoRl5cLI6Fyw6ympRalyg/7f1Hwv90FKUH7MW1LJGnSFKY7+ghlNP1dRGfesoxIC0JS9n2Nh6y6MvcqRFHQmE3Nn2Qi1aN1+8gVCxLVpe7vHdtEh7vQvsBQ12E/zdQRG6ZJDzuwiu1buETzcHmG2/pweF9U2j9Hdm2f/J/9foEkvjGvCA3Xt5nKsrQPfzym1MgE4S8rVUQBo8wviQOINz90Z98pdYb5z8EnS2cQMRzJYS9mOitReRiyskiYxZJf5pKyaO4kXSE+YSG5gFsTZc3H42l0gDpVwvGQAU9b/by389NudIYqHkxvtEgdbBLmKO/p6zstyrAftGNCf2CTyrQvngM9prbf7RvPX+BJhHirTEr0Te6sIIGnlUUpS3Kv65lJqPnAIJ1GUUAO4mwZeAf8gVDXAsaPrXLYxpgb0tlWfhr2uBAUQ/0fEOX0ehrrvrDZ9RSYqsVwdUYJdBTGQjm1N9EWmJECn9hJLVGdS0ID0hi7AnSTldxQ4x3z4PxMnvXIIU7ksU9Uq4QRol3GCQ2X15VwkFOteyI=
